### ISSUE TITLE
toolbar widgets mess

### ISSUE THREAD

**Issue by Neikon** [sirlan-ff00ff/arcticfox-theme#1]
![imagen](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/1765319/8b31a9e0-984c-45c3-b966-eba104eb70ee)

I set like README (I think) but is a mess. Where is the error?
![imagen](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/1765319/833a1337-21e2-44d3-8534-6522aecfdc40)

**Comment by sirlan-ff00ff** [comment]
Remove that icon at the top left that Firefox puts by default, and if you're on Windows there is a section on the CSS to uncomment to make the window buttons smaller (just ctrl f for WINDOWS)

**Comment by Neikon** [comment]
Thanks, Works very well the theme now
![imagen](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/1765319/6cbbe9fc-42e9-4411-98a6-1878d2ede2e9)
