### ISSUE TITLE
[Feature Request] Include the Padlock Icon

### ISSUE THREAD

**Issue by sannidhyaroy** [sirlan-ff00ff/arcticfox-theme#14]
Can you also include the Address/URL bar to show the padlock icon too? Not having the lock icon introduces a chance of going to an unencrypted site or a site without valid SSL configured without getting notified.

**Comment by sirlan-ff00ff** [comment]
The code hiding it is the one with the comment `/* ** hide identity box */` (at around line 142), it can be disabled, or made to show only on hover. Hid it by default as it can take quite a bit of horizontal space
