### ISSUE TITLE
How to change userchrome-toogle icon?

### ISSUE THREAD

**Issue by Neikon** [sirlan-ff00ff/arcticfox-theme#3]
![imagen](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/1765319/2219d575-6f69-4634-a137-2475a673eef4)
How can I change this icon ?

**Comment by Neikon** [comment]
When you say in README sidebar-toogle-button is that button, right?
Note: I found that can be hide and used inside addons buttons

**Comment by sirlan-ff00ff** [comment]
Talking about Firefox's default sidebar button (it needs to be in the toolbar so if you close or are in a private window can open it again), the 'userchrome toggle' button I just leave in the addons menu but you can pin it to the toolbar if you want
